"""Each board's pack/unpack C off the built DBCs, only what it sends or hears. build.py runs it.

    python tools/gen_c.py ECU          -> out/c/ecu/qev6_a.{h,c}, qev6_b.{h,c}
"""
import os
import re
import sys

import cantools
from cantools.database.can.c_source import generate

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
BOARDS = ["ECU"]
CELLS = re.compile(r"^BMU_(Transmit|TRANSMIT_)(Voltage|Temperature|Balancing|VOLTAGE|TEMPERATURE|BALANCING)_N")


def wanted(m, node):
    a = m.dbc.attributes if m.dbc else {}
    if "Status" in a and a["Status"].value == "Legacy":
        return False
    if CELLS.match(m.name):
        return False
    rx = {r for s in m.signals for r in s.receivers}
    return node in m.senders or node in rx


def gen(node):
    out_dir = os.path.join(ROOT, "out", "c", node.lower())
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for bus in ("a", "b"):
        db = cantools.database.load_file(os.path.join(ROOT, "out", f"qev6_can_{bus}.dbc"))
        keep = [m for m in db.messages if wanted(m, node)]
        sub = cantools.database.can.Database(messages=keep, nodes=db.nodes, buses=db.buses, version="",
                                             dbc_specifics=db.dbc)
        name = f"qev6_{bus}"
        h, c, _, _ = generate(sub, name, f"{name}.h", f"{name}.c", "unused_fuzzer.c",
                              floating_point_numbers=False, node_name=node)
        for ext, text in (("h", h), ("c", c)):
            # the date would make every rebuild a diff, the DBC is what versions this
            text = re.sub(r"(generated by cantools version \S+) .*\.", r"\1.", text)
            path = os.path.join(out_dir, f"{name}.{ext}")
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
        written.append(f"{name}: {len(keep)} messages")
    return written


def main():
    for node in sys.argv[1:] or BOARDS:
        print(node, ", ".join(gen(node)))


if __name__ == "__main__":
    main()
