/*
 * CAN_SEVCON.h
 *
 *  Created on: Nov 18, 2023
 *      Author: Calvin
 */

#ifndef INC_CAN_SEVCON_H_
#define INC_CAN_SEVCON_H_

typedef enum {
	SEVCON_STATE_NOT_READY = 0x01,
	SEVCON_STATE_SHUTDOWN = 0x02,
	SEVCON_STATE_PRECHARGE = 0x04,
	SEVCON_STATE_ENERGISED = 0x07,
	SEVCON_STATE_ENABLED = 0x08,
	SEVCON_STATE_FAULT_ACTIVE = 0x0B,
	SEVCON_STATE_FAULT_OFF = 0x0D
} sevcon_state_t;

typedef enum {
	SEVCON_CMD_NONE = 0x00,
	SEVCON_CMD_ENERGISE = 0x03,
	SEVCON_CMD_ENABLE = 0x05,
	SEVCON_CMD_SHUTDOWN = 0x06,
	SEVCON_CMD_FAULT_RESET = 0x09,
	SEVCON_CMD_ACTIVE_SHORT = 0x0A
} sevcon_cmd_t;


#endif /* INC_CAN_SEVCON_H_ */
