/*
 * QUTMS_can.h
 *
 *  Created on: July 4, 2026
 *
 */

#ifndef QUTMS_can_H
#define QUTMS_can_H
#ifdef __cplusplus
extern "C" {
#endif

/* Includes */
#include <stdint.h>

/* Defining Message */
#define Compose_CANId(priority, sourceId, autonomous, type, fd, extra, boardIdx) \
    ((((priority)) << 27 | ((sourceId)) << 22 | ((autonomous)) << 21 | ((type)) << 18 | \
      ((fd)) << 17 | ((extra)) << 4 | ((boardIdx))))

/* Priority */
#define QUTMS_PRIO_ERROR      0x00
#define QUTMS_PRIO_HEARTBEAT  0x01
#define QUTMS_PRIO_NORMAL     0x02
#define QUTMS_PRIO_DEBUG      0x03

/* Source ID */
#define QUTMS_SRC_BMU              0x00
#define QUTMS_SRC_ECU              0x01
#define QUTMS_SRC_ACM              0x02
#define QUTMS_SRC_ROS              0x03
#define QUTMS_SRC_SHUTDOWN         0x04
#define QUTMS_SRC_SW_MOTEC         0x05
#define QUTMS_SRC_CHARGE_CONTROL   0x06

/* System */
#define QUTMS_SYSTEM_EV 0x00
#define QUTMS_SYSTEM_AV 0x01

/* Type */
#define QUTMS_TYPE_ERROR      0x00
#define QUTMS_TYPE_HEARTBEAT  0x01
#define QUTMS_TYPE_TRANSMIT   0x02
#define QUTMS_TYPE_RECIEVE    0x03
#define QUTMS_TYPE_OBJ_DICT   0x04
#define QUTMS_TYPE_STREAM     0x05

/* CAN TYPE */
#define QUTMS_CAN_TYPE_NORMAL 0x00
#define QUTMS_CAN_TYPE_FD 0x01



// MESSAGE IDS

enum CAN_MSG_IDs {
  /* ECU */
  #ifdef QUTMS_CAN_ECU
    QUTMS_ECU_HEARTBEAT Compose_CANId(QUTMS_PRIO_HEARTBEAT, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_HEARTBEAT, QUTMS_CAN_TYPE_NORMAL, 0x00, 0x00),
    QUTMS_ECU_SHUTDOWN_STATUS Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x00, 0x00),
    QUTMS_ECU_PEDAL_ACCEL Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x01, 0x00),
    QUTMS_ECU_PEDAL_BRAKE Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x02, 0x00),
    QUTMS_ECU_GEARBOX_TEMP_LEFT Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x03, 0x00),
    QUTMS_ECU_GEARBOX_TEMP_RIGHT Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x04, 0x00),
    QUTMS_ECU_COOLING_SENSE_1 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x05, 0x00),
    QUTMS_ECU_COOLING_SENSE_2 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x06, 0x00),
    QUTMS_ECU_COOLING_SENSE_3 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x07, 0x00),
    QUTMS_ECU_COOLING_SENSE_4 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x08, 0x00),
    QUTMS_ECU_COOLING_FLOW_RATE Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x09, 0x00),
    QUTMS_ECU_COOLING_PRESSURE Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x0A, 0x00),
    QUTMS_ECU_SUSPENSION_FRONT Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x0B, 0x00),
    QUTMS_ECU_SUSPENSION_REAR Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x0C, 0x00),
    QUTMS_ECU_STEERING_ANGLE Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x0D, 0x00),
    QUTMS_ECU_WHEEL_SPEEDS Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x0E, 0x00),
    QUTMS_ECU_RTD Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_ECU, QUTMS_SYSTEM_EV, QUTMS_TYPE_TRANSMIT, QUTMS_CAN_TYPE_NORMAL, 0x0F, 0x00),
    #endif

  /* ACM */
  #ifdef QUTMS_CAN_ACM
    // leave for now
  #endif

  #ifdef QUTMS_CAN_BMU
    QUTMS_BMU_HEARTBEAT Compose_CANId(QUTMS_PRIO_HEARTBEAT, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_TYPE_HEARTBEAT, QUTMS_CAN_TYPE_NORMAL, 0x00, 0x00),
    QUTMS_BMU_TRANSMIT_VOLTAGE_N_0 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0x00, 0x00),
    QUTMS_BMU_TRANSMIT_VOLTAGE_N_63 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0x3F, 0x00),
    QUTMS_BMU_TRANSMIT_TEMPERATURE_N_0 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0x40, 0x00),
    QUTMS_BMU_TRANSMIT_TEMPERATURE_N_63 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0x7F, 0x00),
    QUTMS_BMU_TRANSMIT_BALANCING_N_0 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0x80, 0x00),
    QUTMS_BMU_TRANSMIT_BALANCING_N_63 Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0xBF, 0x00),
    QUTMS_BMU_TRANSMIT_DIETEMPS Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0xC0, 0x00),
    QUTMS_BMU_TRANSMIT_PACKINFO Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0xD0, 0x00),
    QUTMS_BMU_TRANSMIT_PACKPOWER Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0xD1, 0x00),
    QUTMS_BMU_TRANSMIT_PACKSUMMARY Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0xD2, 0x00),
    QUTMS_BMU_TRANSMIT_POWER Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0xE0, 0x00),
    QUTMS_BMU_TRANSMIT_SOC Compose_CANId(QUTMS_PRIO_NORMAL, QUTMS_SRC_BMU, QUTMS_SYSTEM_EV, QUTMS_CAN_TYPE_NORMAL, 0xF0, 0x00),
  #endif

  #ifdef QUTMS_CAN_CHARGE_CONTROL
    QUTMS_CHARGE_CONTROL_HEARTBEAT Compose_CANId(QUTMS_PRIO_HEARTBEAT, QUTMS_SRC_CHARGE_CONTROL, QUTMS_SYSTEM_EV, QUTMS_TYPE_HEARTBEAT, QUTMS_CAN_TYPE_NORMAL, 0x00, 0x00),
  #endif

  #ifdef QUTMS_CAN_SHDN
    QUTMS_SHDN_SHTUDOWN_TRIGGERED Compose_CANID(QUTMS_PRIO_ERROR, QUTMS_SRC_SHUTDOWN, QUTMS_SYSTEM_EV, QUTMS_TYPE_ERROR, QUTMS_CAN_TYPE_NORMAL, 0x00, 0x00)
  #endif
}
#ifdef __cplusplus
}
#endif
#endif /* QUTMS_can_H */