/*
 * VESC_CAN_Datatypes.h
 *
 *  Created on: 5 Jul 2021
 *      Author: thomas
 */

#ifndef COMMON_INC_VESC_CAN_DATATYPES_H_
#define COMMON_INC_VESC_CAN_DATATYPES_H_

typedef enum _VESC_ID {
	FL = 0,
	FR,
	RL,
	RR
} VESC_ID;

typedef enum _VESC_CAN_PACKET_ID {
	VESC_CAN_PACKET_SET_DUTY = 0,
	VESC_CAN_PACKET_SET_CURRENT,
	VESC_CAN_PACKET_SET_CURRENT_BRAKE,
	VESC_CAN_PACKET_SET_RPM,
	VESC_CAN_PACKET_SET_POS, // Not Implemented
	VESC_CAN_PACKET_FILL_RX_BUFFER, // Not Implemented
	VESC_CAN_PACKET_FILL_RX_BUFFER_LONG, // Not Implemented
	VESC_CAN_PACKET_PROCESS_RX_BUFFER, // Not Implemented
	VESC_CAN_PACKET_PROCESS_SHORT_BUFFER, // Not Implemented
	VESC_CAN_PACKET_STATUS,
	VESC_CAN_PACKET_SET_CURRENT_REL,
	VESC_CAN_PACKET_SET_CURRENT_BRAKE_REL,
	VESC_CAN_PACKET_SET_CURRENT_HANDBRAKE,
	VESC_CAN_PACKET_SET_CURRENT_HANDBRAKE_REL,
	VESC_CAN_PACKET_STATUS_2,
	VESC_CAN_PACKET_STATUS_3,
	VESC_CAN_PACKET_STATUS_4,
	VESC_CAN_PACKET_PING,
	VESC_CAN_PACKET_PONG,
	VESC_CAN_PACKET_DETECT_APPLY_ALL_FOC, // Not Implemented
	VESC_CAN_PACKET_DETECT_APPLY_ALL_FOC_RES, // Not Implemented
	VESC_CAN_PACKET_CONF_CURRENT_LIMITS,
	VESC_CAN_PACKET_CONF_STORE_CURRENT_LIMITS,
	VESC_CAN_PACKET_CONF_CURRENT_LIMITS_IN,
	VESC_CAN_PACKET_CONF_STORE_CURRENT_LIMITS_IN,
	VESC_CAN_PACKET_CONF_FOC_ERPMS, // Not Implemented
	VESC_CAN_PACKET_CONF_STORE_FOC_ERPMS, // Not Implemented
	VESC_CAN_PACKET_STATUS_5,
	VESC_CAN_PACKET_POLL_TS5700N8501_STATUS, // Not Implemented
	VESC_CAN_PACKET_CONF_BATTERY_CUT, // Not Implemented
	VESC_CAN_PACKET_CONF_STORE_BATTERY_CUT, // Not Implemented
	VESC_CAN_PACKET_SHUTDOWN,
	VESC_CAN_PACKET_IO_BOARD_ADC_1_TO_4, // Not Implemented
	VESC_CAN_PACKET_IO_BOARD_ADC_5_TO_8, // Not Implemented
	VESC_CAN_PACKET_IO_BOARD_ADC_9_TO_12, // Not Implemented
	VESC_CAN_PACKET_IO_BOARD_DIGITAL_IN, // Not Implemented
	VESC_CAN_PACKET_IO_BOARD_SET_OUTPUT_DIGITAL, // Not Implemented
	VESC_CAN_PACKET_IO_BOARD_SET_OUTPUT_PWM, // Not Implemented
	VESC_CAN_PACKET_BMS_V_TOT, // Not Implemented
	VESC_CAN_PACKET_BMS_I, // Not Implemented
	VESC_CAN_PACKET_BMS_AH_WH, // Not Implemented
	VESC_CAN_PACKET_BMS_V_CELL, // Not Implemented
	VESC_CAN_PACKET_BMS_BAL, // Not Implemented
	VESC_CAN_PACKET_BMS_TEMPS, // Not Implemented
	VESC_CAN_PACKET_BMS_HUM, // Not Implemented
	VESC_CAN_PACKET_BMS_SOC_SOH_TEMP_STAT // Not Implemented
} VESC_CAN_PACKET_ID;

#endif /* COMMON_INC_VESC_CAN_DATATYPES_H_ */
