#ifdef QUTMS_CAN_SHDN

#include "CAN_SHDN.h"

SHDN_SHUTDOWN_TRIGGERED_t Compose_SHDN_SHUTDOWN_TRIGGERED() {
    SHDN_SHUTDOWN_TRIGGERED_t msg;
    msg.id - QUTMS_SHDN_SHUTDOWN_TRIGGERED;
    return msg;
}